name: perf-test

on:
  
  push:
    branches: [ "jmeter-test" ]
  pull_request:
    branches: [ "jmeter-test" ]

 
  workflow_dispatch:


jobs:
  
  build:
  
    runs-on: ubuntu-latest

   
    steps:
       - uses: actions/checkout@v3
       - name: Install SSH Key
         uses: shimataro/ssh-key-action@v2
         with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

       - name: JMeter Test
         uses: QAInsights/PerfAction@v3.1
         with:
            test-plan-path: './DP-Antuit.jmx'
            args: "--loglevel INFO"
            
       - name: Upload Results
         uses: actions/upload-artifact@v3
         with:
            name: jmeter-results
            path: result.csv
